import { danger, reply, pickRandom } from "./utils.js";

const DB_IMAGE = [
  "Malah Ngirim Gambar Babi Kau",
  "Ngapain kirim gambar sini, gelud lah",
  "nye nye nye apaan gambar monyet",
  "gambar nya kek kontol ajg",
  "gambar jelek jgn di kirim pantek",
  "woi lu tau itu gambar kek kontol",
  "Mau pamer gambar doang, sini gelud kalo berani!",
  "Gambar nggak bikin lu jagoan, sini gelud!",
  "Ngirim gambar terus, sini hadap gua langsung!",
  "Gambar monyet aja berani ngirim, sini maju!",
  "Gambar lu nggak ada nyalinya, sini gelud!",
  "Udah kayak anak kecil, cuma bisa ngirim gambar",
  "Kalo berani, nggak usah kirim gambar, gelud aja!",
  "Ngirim gambar doang, nyali kagak ada?",
  "Gambar nggak bikin lu keren, sini gelud!",
  "Nggak usah banyak gaya pake gambar, sini ketemu!",
  "Gambar nggak ada guna, sini hadap gua!",
  "Ngirim gambar? Dasar pengecut, sini gelud nyata!",
  "Gambar lu cuma buat anak kecil, sini gelud!",
  "Berani ngirim gambar doang, sini hadap gua!",
  "Ngirim gambar? Lucu amat, sini ketemu langsung!",
  "Kalo nyali ada, ngapain main gambar, sini gelud!",
  "Gambar nggak bakal nyelamatin lu, sini gelud!",
  "Bocah gambar takut gelud nyata, sini buktikan!",
  "Cuma berani ngirim gambar, nyali maju kagak ada!",
  "Kalo jagoan, ngapain pake gambar? Sini gelud!",
  "Ngirim gambar buat apa? Kalo berani sini ketemu!",
  "Gambar nggak bikin lu berani, sini maju!",
  "Nggak ada nyali buat gelud nyata, cuma bisa ngirim gambar!",
  "Gambar buat bocah, kalo lu jantan sini ketemu gua!",
  "Ngapain ngirim gambar? Hadap gua langsung kalo berani!",
  "Berani ngirim gambar doang, sini gelud!",
  "Gambar nggak bakal nyelamatin lu, sini hadap gua!",
  "Jangan cuma berani di gambar, sini gelud nyata!",
  "Gambar lu lucu, tapi nyali maju kagak ada!",
  "Kalo lu berani, nggak usah ngirim gambar, gelud aja!",
  "Ngirim gambar cuma buat pengecut, sini hadap gua!",
  "Nggak usah gaya pake gambar, sini hadap langsung!",
  "Gambar nggak ada artinya, kalo berani sini gelud!",
  "Ngirim gambar nggak bikin lu jagoan, sini gelud nyata!",
  "Gambar buat bocah, hadap gua sini kalo berani!",
  "Berani ngirim gambar doang, gelud nyata mana?",
  "Gambar nggak bikin lu keren, sini hadap gua langsung!",
  "Ngapain ngirim gambar, sini ketemu gua!",
  "Kalo lu berani, hadap gua sini, nggak usah pake gambar!",
  "Gambar nggak bakal bikin lu selamat, sini gelud nyata!",
  "Ngirim gambar cuma buat bocah, kalo berani sini ketemu!",
  "Nggak usah ngirim gambar, sini hadap gua kalo berani!",
  "Kalo jagoan, nggak perlu gambar, hadap gua langsung!",
  "Gambar cuma buat yang takut gelud, sini maju!",
];

const DB_STICKER = [
  "Lo Ngirim Sticker di kira gua takut apa kontol",
  "kalo Berani sini gelud, gk usah main sticker babi",
  "dah di bilang kalo berani sini gelud kita, main sticker kek bocah kontol",
  "Ngapain ngirim sticker? Langsung aja gelud kalo berani",
  "Sticker doang, nyali kagak ada? Sini maju!",
  "Udah kayak anak kecil aja, beraninya cuma ngirim sticker",
  "Nggak usah banyak gaya pake sticker, sini hadap gua langsung!",
  "Kalo jagoan, nggak usah ngirim sticker, hadap sini!",
  "Lemah amat cuma berani ngirim sticker, sini gelud nyata!",
  "Sticker lu nggak bakal bikin gua takut, sini maju kalo berani!",
  "Males gua ngeladenin bocah sticker, kalo jantan sini langsung!",
  "Kalo beneran berani, nggak usah pake sticker segala, gelud aja!",
  "Berani ngirim sticker doang, nyali maju kagak ada!",
  "Bocah sticker mana berani gelud beneran, sini buktikan!",
  "Ngirim sticker nggak bakal bikin lu kelihatan berani, gelud sini!",
  "Lo pikir ngirim sticker bikin gua ciut? Sini gelud!",
  "Jangan cuma ngirim sticker, kalo berani sini buktikan!",
  "Sticker nggak ada guna, sini hadap gua langsung!",
  "Ngirim sticker? Dasar pengecut, sini gelud nyata!",
  "Sticker lu cuma buat anak kecil, kalo berani sini kita gelud!",
  "Beraninya cuma di sticker, sini kalo berani hadap gua!",
  "Ngirim sticker? Lucu amat, sini ketemu langsung!",
  "Kalo nyali ada, ngapain main sticker, sini gelud!",
  "Sticker nggak bakal nyelamatin lu, sini gelud!",
  "Bocah sticker takut gelud nyata, sini buktikan kalo berani!",
  "Cuma berani ngirim sticker, nyali maju kagak ada!",
  "Kalo jagoan, ngapain pake sticker? Sini gelud langsung!",
  "Ngirim sticker buat apa? Kalo berani sini ketemu!",
  "Sticker nggak bikin lu berani, sini maju kalo jantan!",
  "Nggak ada nyali buat gelud nyata, cuma bisa ngirim sticker!",
  "Sticker buat bocah, kalo lu jantan sini ketemu gua!",
  "Ngapain ngirim sticker? Hadap gua langsung kalo berani!",
  "Berani ngirim sticker doang, sini gelud kalo jagoan!",
  "Sticker nggak bakal nyelamatin lu, sini hadap gua!",
  "Jangan cuma berani di sticker, sini gelud nyata!",
  "Sticker lu lucu, tapi nyali maju kagak ada!",
  "Kalo lu berani, nggak usah ngirim sticker, gelud aja!",
  "Ngirim sticker cuma buat pengecut, sini hadap gua!",
  "Nggak usah gaya pake sticker, sini hadap langsung!",
  "Sticker nggak ada artinya, kalo berani sini gelud!",
  "Ngirim sticker nggak bikin lu jagoan, sini gelud nyata!",
  "Sticker buat bocah, hadap gua sini kalo berani!",
  "Berani ngirim sticker doang, gelud nyata mana?",
  "Sticker nggak bikin lu keren, sini hadap gua langsung!",
  "Ngapain ngirim sticker, sini ketemu gua!",
  "Kalo lu berani, hadap gua sini, nggak usah pake sticker!",
  "Sticker nggak bakal bikin lu selamat, sini gelud nyata!",
  "Ngirim sticker cuma buat bocah, kalo berani sini ketemu!",
  "Nggak usah ngirim sticker, sini hadap gua kalo berani!",
  "Kalo jagoan, nggak perlu sticker, hadap gua langsung!",
  "Sticker cuma buat yang takut gelud, sini maju kalo jantan!",
  "Sticker nggak ada guna, kalo berani sini hadap gua!",
  "Ngapain ngirim sticker? Sini ketemu gua kalo berani!",
  "Nggak usah gaya pake sticker, kalo jagoan sini ketemu!",
  "Ngirim sticker nggak bikin lu keren, sini gelud nyata!",
  "Sticker buat bocah, kalo berani sini hadap gua!",
  "Ngapain ngirim sticker, sini maju kalo berani!",
  "Kalo lu jagoan, nggak usah pake sticker, hadap gua sini!",
  "Sticker nggak bakal nyelamatin lu, sini hadap langsung!",
  "Beraninya cuma ngirim sticker, sini gelud nyata!",
  "Sticker nggak ada artinya, kalo jantan sini ketemu gua!",
  "Ngirim sticker? Sini ketemu gua langsung!",
  "Sticker nggak bikin lu keren, hadap gua sini kalo berani!",
  "Kalo berani, nggak usah ngirim sticker, gelud aja langsung!",
  "Sticker cuma buat yang takut gelud, sini hadap gua!",
  "Nggak usah banyak gaya pake sticker, kalo jagoan sini ketemu!",
  "Ngirim sticker nggak bikin lu jagoan, sini gelud nyata!",
  "Sticker buat bocah, sini hadap gua kalo berani!",
  "Ngapain ngirim sticker, sini maju kalo lu jagoan!",
  "Kalo lu berani, nggak usah pake sticker, hadap gua sini!",
  "Sticker nggak bakal nyelamatin lu, sini gelud langsung!",
  "Ngirim sticker cuma buat bocah, sini hadap gua kalo berani!",
  "Nggak usah ngirim sticker, sini hadap gua langsung!",
  "Kalo jagoan, nggak perlu sticker, hadap gua sini!",
  "Sticker cuma buat yang takut gelud, sini hadap gua kalo berani!",
  "Sticker nggak ada guna, kalo jantan sini ketemu gua!",
  "Ngapain ngirim sticker? Sini ketemu gua kalo berani!",
  "Nggak usah gaya pake sticker, kalo jagoan sini ketemu gua!",
  "Ngirim sticker nggak bikin lu keren, sini gelud nyata!",
  "Sticker buat bocah, kalo berani sini hadap gua langsung!",
  "Ngapain ngirim sticker, sini maju kalo berani!",
  "Kalo lu jagoan, nggak usah pake sticker, hadap gua sini langsung!",
  "Sticker nggak bakal nyelamatin lu, sini hadap gua kalo jantan!",
  "Beraninya cuma ngirim sticker, sini gelud nyata kalo berani!",
  "Sticker nggak ada artinya, kalo jantan sini ketemu gua langsung!",
  "Ngirim sticker? Sini ketemu gua kalo berani!",
  "Sticker nggak bikin lu keren, hadap gua sini kalo berani!",
  "Kalo berani, nggak usah ngirim sticker, gelud aja langsung sini!",
  "Sticker cuma buat yang takut gelud, sini hadap gua kalo jantan!",
  "Nggak usah banyak gaya pake sticker, kalo jagoan sini ketemu gua langsung!",
  "Ngirim sticker nggak bikin lu jagoan, sini gelud nyata kalo berani!",
  "Sticker buat bocah, sini hadap gua kalo jantan!",
  "Ngapain ngirim sticker, sini maju kalo lu jagoan berani!",
  "Kalo lu berani, nggak usah pake sticker, hadap gua sini langsung!",
  "Sticker nggak bakal nyelamatin lu, sini gelud langsung kalo berani!",
];

const DB_RUSUH = [
  "Apaan lu kontol, mau gelud lawan bot?",
  "wei walaupun gue bot, gua bisa gelud ama lu babi",
  "lu kira lu apa ha",
  "kalau masih punya kontol jangan sok asik deh",
  "woi bajingan",
  "tolol lu ya",
  "Mau gelud sama bot? Lucu lu kontol",
  "Bot aja berani gelud, sini maju lu babi",
  "Jangan sok jago lu, gua bot juga bisa lawan",
  "Lu kira bot ga bisa gelud? Coba aja lu sini",
  "Bot aja ga takut sama lu, kontol",
  "Kalo lu jago, lawan bot sini, babi",
  "Bot juga punya nyali, sini lu hadap gua",
  "Lu pikir bot ga bisa marah? Sini gelud",
  "Walaupun bot, gua ga takut ama lu, kontol",
  "Sini gelud ama bot kalo berani, bangsat",
  "Lu beraninya lawan bot aja, tolol",
  "Bot juga bisa gelud, sini maju lu",
  "Jangan sok jago depan bot, anjing",
  "Gua bot tapi bisa lawan lu, sini kalo nyali ada",
  "Bot juga bisa marah, sini hadap gua, babi",
  "Beraninya lawan bot doang, dasar pengecut",
  "Lu kira bot ga punya nyali? Sini coba",
  "Bot juga bisa hajar lu, sini maju, kontol",
  "Jangan kira bot ga bisa lawan, sini lu",
  "Bot aja berani lawan, lu berani ga?",
  "Walaupun bot, gua bisa gelud, sini maju",
  "Sok jago lu depan bot, sini hadap gua",
  "Bot juga bisa gebukin lu, sini kalo nyali ada",
  "Lu kira gua takut karena gua bot? Kontol",
  "Beraninya lawan bot doang, dasar pengecut lu",
  "Lu ga ada nyali lawan bot aja takut, anjing",
  "Bot juga bisa ngelawan, sini hadap gua",
  "Jangan sok jago kalo lu cuma lawan bot, babi",
  "Walaupun bot, gua berani hadap lu, sini maju",
  "Lu pikir bot cuma diem? Sini gelud",
  "Bot aja bisa hajar lu, sini hadap gua",
  "Jangan kira bot ga bisa gelud, coba aja",
  "Bot juga punya nyali, sini lu babi",
  "Gua bot tapi bisa lawan, sini kalo berani",
  "Beraninya sama bot doang, tolol",
  "Lu kira bot ga bisa hajar? Sini coba",
  "Bot juga bisa ngamuk, sini hadap gua, kontol",
  "Lu pikir bot cuma bisa diem? Sini maju",
  "Bot juga bisa gelud, sini hadap gua kalo jagoan",
  "Jangan sok jago depan bot, coba sini",
  "Bot juga bisa ngelawan, sini maju kalo berani",
  "Lu kira bot ga ada nyali? Sini coba hadap gua",
  "Bot juga bisa marah, sini lu kontol",
  "Jangan sok jago kalo lu lawan bot doang, sini maju",
];

const DB_MAX = [
  "Apaan lu kontol, babi kau",
  "setan kau anjing",
  "lu kira gua takut ama lu",
  "woi kontol ajg",
  "apaan sok asik monyet",
  "Lu lagi diem napa muka kek kontol",
  "bangsat kau, jgn sok asik kontol",
  "ikan hiu makan tomat \nBodo amat kontol",
  "lu anjing kocak",
  "woi babi, sini maju",
  "muka lu kek monyet, gausah sok asik",
  "woi kontol, jgn sok jago lu",
  "lu kira gua peduli, bangsat",
  "muka lu kayak setan, apaan sok asik",
  "kontol, sini kalo berani",
  "sini maju, anjing",
  "lu pikir gua takut? Kontol!",
  "monyet, gausah banyak omong",
  "lu anjing, gausah sok asik",
  "woi bangsat, sini ketemu gua",
  "kontol, jangan banyak gaya lu",
  "lu kira gua takut ama muka jelek lu?",
  "bangsat, sini kalo jago",
  "anjing, lu ga bakal berani hadap gua",
  "kontol, lu ga ada nyali",
  "woi babi, gausah sok jago",
  "sok asik lu anjing, sini gelud",
  "setan, jgn banyak omong",
  "kontol, sini kalo nyali ada",
  "muka lu kayak babi, gausah sok asik",
  "lu pikir gua takut ama omongan lu, bangsat",
  "anjing, sini maju kalo berani",
  "woi kontol, diem lu",
  "muka lu kek monyet, apaan sok asik",
  "kontol, sini hadap gua",
  "bangsat, lu ga bakal berani",
  "anjing, lu cuma bisa omong doang",
  "kontol, lu pikir gua takut?",
  "woi babi, lu ga ada nyali",
  "sok asik lu anjing, sini ketemu gua",
  "setan, lu ga bakal berani hadap gua",
  "kontol, jangan banyak omong",
  "lu kira gua takut ama muka jelek lu, bangsat",
  "anjing, sini gelud kalo nyali ada",
  "kontol, lu ga ada nyali",
  "woi bangsat, lu cuma bisa omong doang",
  "kontol, sini hadap gua kalo berani",
  "anjing, lu pikir gua takut?",
  "muka lu kayak babi, gausah sok asik",
  "kontol, lu ga bakal berani hadap gua",
  "Apaan lu kontol, babi kau",
  "setan kau anjing",
  "lu kira gua takut ama lu",
  "woi kontol ajg",
  "apaan sok asik monyet",
  "Lu lagi diem napa muka kek kontol",
  "bangsat kau, jgn sok asik kontol",
  "ikan hiu makan tomat \nBodo amat kontol",
  "lu anjing kocak",
  "woi babi, sini maju",
  "muka lu kek monyet, gausah sok asik",
  "woi kontol, jgn sok jago lu",
  "lu kira gua peduli, bangsat",
  "muka lu kayak setan, apaan sok asik",
  "kontol, sini kalo berani",
  "sini maju, anjing",
  "lu pikir gua takut? Kontol!",
  "monyet, gausah banyak omong",
  "lu anjing, gausah sok asik",
  "woi bangsat, sini ketemu gua",
  "kontol, jangan banyak gaya lu",
  "lu kira gua takut ama muka jelek lu?",
  "bangsat, sini kalo jago",
  "anjing, lu ga bakal berani hadap gua",
  "kontol, lu ga ada nyali",
  "woi babi, gausah sok jago",
  "sok asik lu anjing, sini gelud",
  "setan, jgn banyak omong",
  "kontol, sini kalo nyali ada",
  "muka lu kayak babi, gausah sok asik",
  "lu pikir gua takut ama omongan lu, bangsat",
  "anjing, sini maju kalo berani",
  "woi kontol, diem lu",
  "muka lu kek monyet, apaan sok asik",
  "kontol, sini hadap gua",
  "bangsat, lu ga bakal berani",
  "anjing, lu cuma bisa omong doang",
  "kontol, lu pikir gua takut?",
  "woi babi, lu ga ada nyali",
  "sok asik lu anjing, sini ketemu gua",
  "setan, lu ga bakal berani hadap gua",
  "kontol, jangan banyak omong",
  "lu kira gua takut ama muka jelek lu, bangsat",
  "anjing, sini gelud kalo nyali ada",
  "kontol, lu ga ada nyali",
  "woi bangsat, lu cuma bisa omong doang",
  "kontol, sini hadap gua kalo berani",
  "anjing, lu pikir gua takut?",
  "muka lu kayak babi, gausah sok asik",
  "kontol, lu ga bakal berani hadap gua",
  "Lu kira gua takut ama muka jelek lu, kontol",
  "Wo lu kontol, sok asik aja",
  "Nggak usah gaya lu, kontol",
  "Muka lu kayak setan, anjing",
  "Woi babi, jangan sok kuat lu",
  "Lu pikir gua takut? Babi!",
  "Gak usah banyak omong, bangsat",
  "Anjing, lu berani hadap gua gak?",
  "Kontol, jangan banyak gaya",
  "Setan, lu pikir gua takut?",
  "Monyet, sini kalo nyali ada",
  "Babi, lu cuma bisa ngomong doang",
  "Bangsat, lu gak bakal berani",
  "Kontol, lu pikir gua takut ama lu?",
  "Lu kira gua peduli? Setan!",
  "Sok asik lu anjing, gua nggak takut",
  "Lu pikir gua takut ama muka jelek lu?",
  "Anjing, sini maju kalo berani",
  "Kontol, lu ga ada nyali",
  "Babi, lu cuma bisa omong doang",
  "Bangsat, lu gak bakal berani hadap gua",
  "Kontol, sini hadap gua kalo jagoan",
  "Anjing, lu pikir gua takut ama lu?",
  "Monyet, gausah sok asik",
  "Setan, lu gak bakal berani hadap gua",
  "Kontol, jangan banyak omong",
  "Babi, lu cuma bisa ngomong doang",
  "Bangsat, sini hadap gua kalo berani",
  "Kontol, lu pikir gua takut ama lu?",
  "Anjing, sini maju kalo nyali ada",
  "Setan, gua gak takut ama lu",
  "Kontol, sini hadap gua kalo jago",
  "Bangsat, lu ga bakal berani",
  "Babi, gua gak takut ama lu",
  "Anjing, lu cuma bisa ngomong doang",
  "Kontol, lu pikir gua takut ama lu?",
  "Setan, lu ga bakal berani hadap gua",
  "Kontol, jangan banyak gaya lu",
  "Anjing, sini maju kalo nyali ada",
  "Babi, gua gak takut ama lu",
];

const processingChats = {};

async function autoRusuh(sock, messageInfo, isQuotedMe) {
  const {
    m,
    remoteJid,
    id,
    command,
    isQuoted,
    content,
    message,
    sender,
    pushName,
    type,
    fullText,
  } = messageInfo;

  // Cek apakah chat ini sedang diproses
  if (processingChats[remoteJid]) {
    console.log(`Chat dari ${remoteJid} sedang diproses. Menunggu...`);
    return; // Tidak melayani chat lainnya sampai yang sebelumnya selesai
  }

  // Tandai chat ini sebagai sedang diproses
  processingChats[remoteJid] = true;

  try {
    if (type == "image") {
      await reply(m, pickRandom(DB_IMAGE));
      return;
    }

    if (type == "sticker") {
      await reply(m, pickRandom(DB_STICKER));
      return;
    }

    if (fullText.toLowerCase().includes("bot")) {
      await reply(m, pickRandom(DB_RUSUH));
      return;
    }

    if (isQuotedMe) {
      await reply(m, pickRandom(DB_MAX));
      return;
    }
  } catch (error) {
    // Menangani kesalahan dan log dengan baik
    danger(command, `Kesalahan di lib/autorusuh.js: ${error.message}`);
    await reply(m, `_Terjadi kesalahan: ${error.message}_`);
  } finally {
    // Hapus status proses setelah selesai
    delete processingChats[remoteJid];
  }
}

export default autoRusuh;
